//! The statement merge: an entity body is a container in miniature.
//!
//! `container.rs` gave a class body the discipline `region.rs` gives a file —
//! DECOMPOSE into segments that tile the input, merge the segments by identity,
//! fold the results back. This module is the same move one level further down,
//! and it is the last one: when both sides edit the same *function* body and
//! diff3 refuses it, the body is partitioned into STATEMENTS, the statement
//! triples are classified with the same actions the entity triples use,
//! and the merge is a fold over the partition.
//!
//! Three properties are load-bearing, and each is structural rather than
//! argued:
//!
//!   1. **Partition identity.** `header + prelude + Σ(lead + text) + tail +
//!      footer` reproduces the input byte for byte. The pieces tile the body,
//!      so "a stage rebuilt text out of the pieces it understood, and whatever
//!      it did not understand ceased to exist" is not a sentence this module
//!      can be the subject of.
//!
//!   2. **Linear claims.** A `Part` is moved into exactly one triple by a
//!      claim token — `BasePart` / `OursPart` / `TheirsPart`, three distinct
//!      types generated by the `part_claim!` macro, none of them `Copy` or
//!      `Clone`, all of them minted only by the partitioner. A statement byte is therefore owned once: emitting one
//!      statement twice is a program that does not compile, exactly as
//!      `v2::types::Claim` makes it for entities.
//!
//!   3. **Refinement, never trade.** This merge is reached only from a position
//!      that is *already* a conflict — after `diffy`, after `git merge-file`,
//!      after the decorator merge, after the container merge. Every verdict it
//!      can change is therefore CONFLICT → something; no clean merge in the
//!      universe routes through here, so no clean merge can be turned into a
//!      different clean merge by it. So this pass can only turn a conflict into
//!      something else, never a clean merge into a different one — and the tests
//!      check that directly anyway, because an argument nobody runs is a comment.
//!
//! The container is ORDER-EFFECTFUL. Members of a class are unordered children;
//! statements of a body are a sequence, and executing them in the other order
//! is a different program. So placement here is not `container::member_order`'s
//! "shared base coordinate" — it is the order-preserving union of what the two
//! sides asserted, with an honest conflict wherever the two assertions
//! interleave ambiguously (two independent insertions into the SAME gap have no
//! separator between them, so choosing an order for them is choosing a program
//! neither side wrote).
//!
//! Recursion stops at a COUNTER, not at an argument. A statement that is itself
//! a block — an `if`, a `for`, a `switch` — is partitioned again by the same
//! fold when diff3 refuses it, down to [`MAX_DEPTH`]. The bound is not decoration:
//! a body whose partition is a single block statement recurses on text that is
//! very nearly itself, so "the input shrinks" is not available as a termination
//! measure and the depth counter is the well-founded one.
//!
//! Below the bottom level, and below a statement that is not a block, there is
//! one more partition and then there is diff3. Two disjoint edits to a single
//! LINE used to stay a conflict here, because composing them needs a partition
//! into TOKENS and that partition's failure mode is new — a syntactically valid
//! sentence neither side wrote. [`crate::expression`] is
//! that partition, and it is reached from exactly one arm of this module: the
//! `(Edited, Edited)` cell, after `formatting_tie`, after diff3, after the block
//! recursion, immediately before the marker. It answers `None` for everything it
//! is not sure of, so the arm it sits in still writes the same marker it always
//! did unless a composition is licensed outright.
//!
//! That one addition is what makes [`fabricates_lines`] take an allowlist. A
//! token composition is a line no version wrote — that is what composing means —
//! so the backstop is told exactly which lines were composed and admits those
//! and nothing else.

use std::collections::HashMap;

use crate::binding::{declared_name, footprint, footprints_disjoint, is_trivia_line, word_tokens};
use crate::container::{drops_unanimous_lines, InnerMergeResult};
use crate::merge::ScopeMarkers;
use crate::merge::{diffy_merge, scoped_conflict_marker};

// ---------------------------------------------------------------------------
// Claims: the right to place one statement in one triple
// ---------------------------------------------------------------------------

/// A move-once handle naming one statement of one version. Neither `Copy` nor
/// `Clone`, minted only by [`partition`], spent exactly once by the fold.
///
/// One type per version, so a base statement cannot be dropped into the ours
/// slot — the same trick `v2::types` plays for entities, for the same reason.
macro_rules! part_claim {
    ($name:ident) => {
        #[derive(Debug, PartialEq, Eq)]
        pub(crate) struct $name(usize);
        impl $name {
            fn new(i: usize) -> Self {
                Self(i)
            }
            fn index(&self) -> usize {
                self.0
            }
        }
    };
}

part_claim!(BasePart);
part_claim!(OursPart);
part_claim!(TheirsPart);

// ---------------------------------------------------------------------------
// The partition
// ---------------------------------------------------------------------------

/// One statement, with the unclaimed text that leads it.
#[derive(Debug, Clone)]
struct Part {
    /// The statement's structural key: its own text with per-line trailing
    /// whitespace and leading indentation removed, so a statement that only
    /// moved (and was re-indented by the move) still matches itself.
    key: String,
    /// Blank lines and section comments between the previous statement and this
    /// one's first own line. Travels with the statement it leads.
    lead: String,
    text: String,
}

/// One version of a body, tiled.
///
/// `header + prelude + Σ(lead + text) + tail + footer` reproduces the input
/// exactly. That equation is the property the whole module rests on and it is
/// asserted directly by `a_partition_tiles_the_body_it_came_from`.
#[derive(Debug)]
struct Partition {
    header: String,
    /// Text between the declaration and the first statement. A segment of the
    /// BODY, not of the statement that happens to follow it — the same reason
    /// `container::Decomposed::prelude` exists.
    prelude: String,
    parts: Vec<Part>,
    tail: String,
    footer: String,
}

impl Partition {
    /// Mint one claim per statement. The only constructor there is, so the
    /// claim multiset is exactly the statement multiset.
    fn claims<T>(&self, mk: impl Fn(usize) -> T) -> Vec<T> {
        (0..self.parts.len()).map(mk).collect()
    }
}

/// Join line slices back into text, one newline per line.
fn join(lines: &[&str]) -> String {
    let mut s = String::new();
    for l in lines {
        s.push_str(l);
        s.push('\n');
    }
    s
}

/// The structural key of a statement: content, normalized for the things that
/// are not content.
///
/// Trailing whitespace is not content. Leading indentation is not content
/// *of the statement* — a statement that moved from one block to another is the
/// same statement, re-indented — but it IS content of the file, which is why
/// the key is used only for MATCHING and never for emitting: what gets written
/// out is always some side's own bytes.
fn statement_key(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for line in text.lines() {
        let t = line.trim();
        if t.is_empty() {
            continue;
        }
        out.push_str(t);
        out.push('\n');
    }
    out
}

/// How much two unmatched statements in one gap look like each other — the only
/// question that decides whether they are one statement EDITED or a DELETE
/// standing beside an ADD.
///
/// Two readings, and the generous one wins. Word Jaccard is the right measure
/// for a statement with words in it; it is *useless* on the short ones that
/// dominate real bodies — `b();` and `b(2);` share no whitespace-delimited
/// token at all, so a word-only measure calls an edit of a one-call statement a
/// deletion, and then the other side's edit to it is a conflict rather than a
/// merge. Character bigrams see what words cannot at that length.
fn similarity(a: &str, b: &str) -> f64 {
    words_jaccard(a, b).max(bigram_jaccard(a, b))
}

fn jaccard<T: std::hash::Hash + Eq>(a: impl Iterator<Item = T>, b: impl Iterator<Item = T>) -> f64 {
    use std::collections::HashSet;
    let ta: HashSet<T> = a.collect();
    let tb: HashSet<T> = b.collect();
    if ta.is_empty() && tb.is_empty() {
        return 1.0;
    }
    let inter = ta.intersection(&tb).count() as f64;
    let union = ta.union(&tb).count() as f64;
    if union == 0.0 {
        0.0
    } else {
        inter / union
    }
}

fn words_jaccard(a: &str, b: &str) -> f64 {
    jaccard(word_tokens(a).into_iter(), word_tokens(b).into_iter())
}

fn bigram_jaccard(a: &str, b: &str) -> f64 {
    fn grams(s: &str) -> Vec<(char, char)> {
        let cs: Vec<char> = s.chars().filter(|c| !c.is_whitespace()).collect();
        cs.windows(2).map(|w| (w[0], w[1])).collect()
    }
    jaccard(grams(a).into_iter(), grams(b).into_iter())
}

// ---------------------------------------------------------------------------
// Nesting depth: the veto that makes indentation trustworthy
// ---------------------------------------------------------------------------

/// Bracket depth *before* each line of `lines`, or `None` if the scan cannot be
/// trusted.
///
/// Indentation alone says a statement starts wherever a line returns to the
/// body's own column — which is false for any statement whose continuation
/// lines were not indented, and those are everywhere in real code:
///
/// ```text
/// foo(a,
/// b);
/// ```
///
/// So indentation proposes and depth vetoes: a line begins a statement only if
/// every bracket opened before it has been closed. When the scan ends
/// unbalanced the text is not something this reader understands — a language
/// with delimiters we do not model, an unclosed literal — and the honest answer
/// is `None`, which costs a conflict and never a wrong partition.
///
/// Quotes are resolved WITHIN a line: an opener with no closer on the same line
/// is not a string. That one rule is what lets the same scanner read Rust
/// lifetimes (`&'a str` — an apostrophe that opens nothing) and Python string
/// literals (`'x'` — one that does), without being told which language it is
/// looking at. Multi-line literals are exactly the two constructs that really do
/// span lines: block comments and triple quotes.
fn depths(lines: &[&str]) -> Option<Vec<i32>> {
    let mut out = Vec::with_capacity(lines.len());
    let mut depth: i32 = 0;
    let mut in_block_comment = false;
    let mut in_triple: Option<&'static str> = None;

    for line in lines {
        out.push(depth);
        let chars: Vec<char> = line.chars().collect();
        let offsets: Vec<usize> = line.char_indices().map(|(b, _)| b).collect();
        let rest_from = |i: usize| -> &str { &line[offsets[i]..] };
        let mut i = 0usize;
        while i < chars.len() {
            let c = chars[i];
            if let Some(q) = in_triple {
                if rest_from(i).starts_with(q) {
                    in_triple = None;
                    i += 3;
                } else {
                    i += 1;
                }
                continue;
            }
            if in_block_comment {
                if c == '*' && chars.get(i + 1) == Some(&'/') {
                    in_block_comment = false;
                    i += 2;
                } else {
                    i += 1;
                }
                continue;
            }
            let rest = rest_from(i);
            if rest.starts_with("\"\"\"") {
                in_triple = Some("\"\"\"");
                i += 3;
                continue;
            }
            if rest.starts_with("'''") {
                in_triple = Some("'''");
                i += 3;
                continue;
            }
            if rest.starts_with("/*") {
                in_block_comment = true;
                i += 2;
                continue;
            }
            if rest.starts_with("//") || c == '#' {
                break; // line comment (or a `#[attr]`, whose brackets balance)
            }
            if c == '"' || c == '\'' || c == '`' {
                match close_on_line(&chars, i, c) {
                    Some(end) => {
                        i = end + 1;
                        continue;
                    }
                    // No closer on this line: not a literal opener at all
                    // (a Rust lifetime, an English apostrophe in a comment we
                    // did not recognise). Read it as an ordinary character.
                    None => {
                        i += 1;
                        continue;
                    }
                }
            }
            match c {
                '(' | '[' | '{' => depth += 1,
                ')' | ']' | '}' => depth -= 1,
                _ => {}
            }
            i += 1;
        }
    }
    // An unterminated literal is the one state this reader cannot recover from:
    // everything after it was read as code that is not code, and no baseline
    // shift repairs that. An unbalanced *bracket* count is a different thing —
    // it means the text handed in is a fragment of something larger, which is
    // exactly what a recursive fold hands itself, and `statement_spans` reads
    // depth relative to the fragment's own level rather than to zero.
    if in_block_comment || in_triple.is_some() {
        return None;
    }
    Some(out)
}

/// Index of the closing quote matching the opener at `start`, on this line.
fn close_on_line(chars: &[char], start: usize, quote: char) -> Option<usize> {
    let mut i = start + 1;
    while i < chars.len() {
        if chars[i] == '\\' {
            i += 2;
            continue;
        }
        if chars[i] == quote {
            return Some(i);
        }
        i += 1;
    }
    None
}

// ---------------------------------------------------------------------------
// Statement spans
// ---------------------------------------------------------------------------

/// Does this line continue the statement above it rather than start a new one?
///
/// Depth already answers that for anything inside brackets. What it cannot see
/// is the *grammatical* continuation that closes one block and opens the next
/// at the same depth and the same column — `} else {`, `elif`, `except`,
/// `finally`, `case`. Splitting there would hand the fold two half-statements
/// whose bodies could then be merged in either order, which is exactly the
/// interleaving this module exists to refuse.
fn is_continuation(trimmed: &str, prev: &str) -> bool {
    // A blank line starts nothing, so it continues whatever came before it.
    // Written as the `else` of the lookup rather than as a separate guard above
    // it: the guard and the `.unwrap()` that followed said the same thing
    // twice, and only one of them was checked by the compiler.
    let Some(first) = trimmed.chars().next() else {
        return true;
    };
    if matches!(
        first,
        '}' | ')' | ']' | ',' | '.' | '?' | ':' | ';' | '+' | '*' | '/' | '|' | '&' | '=' | '<'
    ) {
        return true;
    }
    let word = |k: &str| {
        trimmed == k
            || trimmed.starts_with(&format!("{k}:"))
            || trimmed.starts_with(&format!("{k} "))
            || trimmed.starts_with(&format!("{k}("))
            || trimmed.starts_with(&format!("{k}{{"))
    };
    const ARMS: [&str; 7] = [
        "else", "elif", "except", "finally", "catch", "when", "rescue",
    ];
    if ARMS.iter().any(|k| word(k)) {
        return true;
    }
    // `case` and `default` are the arms of a switch, and inside a switch body
    // they are the statement STARTS, not continuations — a switch whose arms
    // nobody can see is one statement, and two sides editing different arms of
    // it is then one conflict instead of two clean edits. What genuinely
    // continues is a fall-through LABEL: `case A:` immediately under `case B:`
    // with no body between them is one arm written on two lines.
    if word("case") || word("default") {
        return prev.ends_with(':');
    }
    false
}

/// Inclusive line spans of the statements in `lines[body_start..body_end)`.
///
/// A statement begins at the first column the body uses, at bracket depth zero,
/// on a line that neither continues the statement above it nor is trivia
/// belonging to the statement below it.
fn statement_spans(
    lines: &[&str],
    body_start: usize,
    body_end: usize,
) -> Option<Vec<(usize, usize)>> {
    if body_start >= body_end {
        return None;
    }
    let depth = depths(&lines[body_start..body_end])?;
    let first = lines[body_start..body_end]
        .iter()
        .position(|l| !l.trim().is_empty())?;
    let body_indent = {
        let l = lines[body_start + first];
        l.len() - l.trim_start().len()
    };
    // The fragment's OWN nesting level, not zero. A body sliced out of a larger
    // construct starts wherever it starts, and its statements are the lines that
    // return to that level.
    let base_depth = depth[first];

    let mut starts: Vec<usize> = Vec::new();
    let mut prev_code = "";
    for (off, line) in lines[body_start..body_end].iter().enumerate() {
        let trimmed = line.trim();
        if trimmed.is_empty() || is_trivia_line(line) {
            continue;
        }
        let prev = std::mem::replace(&mut prev_code, trimmed);
        if depth[off] != base_depth {
            continue;
        }
        let indent = line.len() - line.trim_start().len();
        if indent > body_indent {
            continue;
        }
        if is_continuation(trimmed, prev) {
            continue;
        }
        starts.push(body_start + off);
    }
    if starts.is_empty() {
        return None;
    }

    let mut spans: Vec<(usize, usize)> = Vec::new();
    for (i, &s) in starts.iter().enumerate() {
        let mut end = starts.get(i + 1).map(|n| n - 1).unwrap_or(body_end - 1);
        // Trailing blank lines and the next statement's own comment belong to
        // that statement's lead, so a deletion takes its own separator with it
        // and a comment travels with the thing it documents.
        while end > s && (lines[end].trim().is_empty() || is_trivia_line(lines[end])) {
            end -= 1;
        }
        spans.push((s, end));
    }
    Some(spans)
}

/// Walk back over the decorators, annotations and doc comment that belong to a
/// statement, stopping at `floor`.
fn attach_leading_trivia(lines: &[&str], start: usize, floor: usize) -> usize {
    let mut own = start;
    while own > floor && is_trivia_line(lines[own - 1]) {
        own -= 1;
    }
    own
}

/// (first body line, first footer line) for a BLOCK — a line that opens a
/// scope, whose body is the more-indented run beneath it.
///
/// Deliberately narrow: the opener must be the fragment's first non-blank line,
/// what follows it must be indented further, and a brace block must close on the
/// fragment's last non-blank line at the opener's own column. Anything looser
/// starts treating `data = {` as a scope and its entries as statements of the
/// enclosing body, which is how a reconstruction learns to move text.
fn block_wrapper(lines: &[&str]) -> Option<(usize, usize)> {
    let h = lines.iter().position(|l| !l.trim().is_empty())?;
    let opener = lines[h].trim_end();
    let indent = |l: &str| l.len() - l.trim_start().len();
    let next = lines[h + 1..].iter().position(|l| !l.trim().is_empty())? + h + 1;
    if indent(lines[next]) <= indent(lines[h]) {
        return None;
    }
    if opener.ends_with(':') {
        return Some((h + 1, lines.len()));
    }
    if opener.ends_with('{') {
        let last = lines.iter().rposition(|l| !l.trim().is_empty())?;
        if last > next
            && crate::merge::is_container_close_line(lines[last].trim())
            && indent(lines[last]) <= indent(lines[h])
        {
            return Some((h + 1, last));
        }
    }
    None
}

/// Tile a body into header / prelude / statements / tail / footer.
fn partition(content: &str) -> Option<Partition> {
    let lines: Vec<&str> = content.lines().collect();
    if lines.len() < 2 {
        return None;
    }
    // A body may or may not be wrapped. A function region is `fn f() { … }`; a
    // class attribute block or an interstitial run of statements is not wrapped
    // at all, and reading it as unwrapped is the honest reading rather than a
    // degradation.
    let (header_end, body_end) = match crate::merge::extract_container_wrapper(content) {
        Some((header, footer)) => {
            // Both pieces are slices OF `content` — a prefix and a suffix — so
            // the body's bounds are read off them directly rather than
            // recovered by a subtraction that would then need repairing. The
            // two sides cannot disagree about a length they do not both compute.
            let he = header.lines().count();
            let be = content[..content.len() - footer.len()].lines().count();
            if he > be {
                return None;
            }
            (he, be)
        }
        // `extract_container_wrapper` knows about declarations — `class`, `def`,
        // a brace on the signature line. A BLOCK is not a declaration, and the
        // recursive arm hands itself blocks: `if cond:` … , `for x in y {` … `}`.
        // Without this the fold recurses into a Python `if` and finds one
        // statement (the `if` itself), which is the shape it started from, so it
        // never looks inside a conditional in an indentation-scoped language at
        // all.
        None => block_wrapper(&lines).unwrap_or((0, lines.len())),
    };

    let spans = statement_spans(&lines, header_end, body_end)?;

    let mut parts: Vec<Part> = Vec::new();
    let mut cursor = header_end;
    for (i, &(start, end)) in spans.iter().enumerate() {
        let floor = if i == 0 { header_end } else { cursor };
        let own_start = attach_leading_trivia(&lines, start, floor);
        let lead = join(&lines[cursor..own_start]);
        let text = join(&lines[own_start..=end]);
        parts.push(Part {
            key: statement_key(&text),
            lead,
            text,
        });
        cursor = end + 1;
    }

    let prelude = parts
        .first_mut()
        .map(|p| std::mem::take(&mut p.lead))
        .unwrap_or_default();

    Some(Partition {
        header: join(&lines[..header_end]),
        prelude,
        parts,
        tail: join(&lines[cursor..body_end]),
        footer: join(&lines[body_end..]),
    })
}

// ---------------------------------------------------------------------------
// Classification: the same actions, one level down
// ---------------------------------------------------------------------------

/// What one side did to one base statement. The entity actions,
/// restricted to the actions a statement can carry: statements have no name
/// distinct from their content, so RENAMED and RENAME+EDITED collapse into
/// EDITED.
#[derive(Debug, Clone, PartialEq)]
enum Action {
    Unchanged,
    /// The side's index for the statement this base statement became.
    Edited(usize),
    Deleted,
}

/// The same action, holding the statement it acted on rather than an index
/// into a table the reader has to trust.
///
/// `Action::Edited(s)` says a side's statement `s` exists; resolving `s`
/// against that side's parts is a separate step, and for as long as the two
/// travelled separately — an `Action` beside an `Option<&Part>` — every cell of
/// the merge table that needed the statement reached for it with `.unwrap()`.
/// Six of them did. The implication was true, and enforced by nothing but the
/// match arm above each call: exactly the shape of gap that turns into a
/// runtime panic the day one arm's assumption stops holding, because nothing
/// in the type checks it.
///
/// Here the statement rides inside the variant, so `Edited` without a statement
/// does not exist to be unwrapped, and the match arms read it by binding it.
#[derive(Debug)]
enum SideEdit<'a> {
    Unchanged,
    Edited(&'a Part),
    Deleted,
}

impl<'a> SideEdit<'a> {
    /// Resolve one side's action against that side's parts, once, at the only
    /// place the action index and that side's table are both in scope.
    ///
    /// `locate` spends the side's claim — one claim type per version, so this
    /// stays a closure rather than a shared trait and a base claim still cannot
    /// be handed to the ours slot.
    fn resolve(action: &Action, parts: &'a [Part], locate: impl Fn(usize) -> usize) -> Self {
        match action {
            Action::Unchanged => SideEdit::Unchanged,
            // `align` writes `Edited(s)` only for an `s` it read out of this
            // side's own claim vector, and both vectors are minted once from
            // this side's partition — so the index is in range by construction.
            Action::Edited(s) => SideEdit::Edited(&parts[locate(*s)]),
            Action::Deleted => SideEdit::Deleted,
        }
    }

    /// The statement this side still has, for the trivia rules that ask about
    /// a side without caring whether it edited.
    fn part(&self) -> Option<&'a Part> {
        match self {
            SideEdit::Edited(p) => Some(p),
            _ => None,
        }
    }
}

/// One side's reading of the base sequence.
#[derive(Debug)]
struct Alignment {
    /// One action per base statement.
    per_base: Vec<Action>,
    /// `(gap, side index)` for each statement this side added, where `gap` is
    /// the base index the addition sits BEFORE (`base.len()` = at the end).
    additions: Vec<(usize, usize)>,
}

/// Longest common subsequence of two key sequences, as index pairs.
///
/// Bounded: a body with more statements than `MAX_LCS` cells is not merged at
/// statement level at all, because a quadratic table on an unbounded input is a
/// latency regression waiting for the one file that has it.
const MAX_LCS: usize = 250_000;

fn lcs_pairs(a: &[String], b: &[String]) -> Option<Vec<(usize, usize)>> {
    if a.len().saturating_mul(b.len()) > MAX_LCS {
        return None;
    }
    let (n, m) = (a.len(), b.len());
    let mut table = vec![0u32; (n + 1) * (m + 1)];
    let at = |i: usize, j: usize| i * (m + 1) + j;
    for i in (0..n).rev() {
        for j in (0..m).rev() {
            table[at(i, j)] = if a[i] == b[j] {
                table[at(i + 1, j + 1)] + 1
            } else {
                table[at(i + 1, j)].max(table[at(i, j + 1)])
            };
        }
    }
    let mut pairs = Vec::new();
    let (mut i, mut j) = (0usize, 0usize);
    while i < n && j < m {
        if a[i] == b[j] {
            pairs.push((i, j));
            i += 1;
            j += 1;
        } else if table[at(i + 1, j)] >= table[at(i, j + 1)] {
            i += 1;
        } else {
            j += 1;
        }
    }
    Some(pairs)
}

/// The similarity two unmatched statements in one gap need before they are read
/// as one statement EDITED rather than as a DELETE beside an ADD.
///
/// A wrong pairing here is not a loss — both readings keep every byte — but it
/// decides whether the other side's edit to the same statement is a merge or a
/// conflict, so the gate is set where an edit still looks like its origin.
const EDIT_SIMILARITY: f64 = 0.4;

/// The order-preserving matching of two unmatched runs that maximises total
/// similarity, keeping only pairs above [`EDIT_SIMILARITY`].
///
/// Ties are broken toward matching (and then toward advancing `a`), so the
/// result is a function of the two runs and nothing else — the comparison is on
/// integers scaled from the score rather than on floats, because a fold whose
/// shape depends on float association order is not a function either.
fn best_matching(a: &[String], b: &[String]) -> Vec<(usize, usize)> {
    /// Tighter than `MAX_LCS`, because each cell here costs a similarity
    /// computation over two whole statements rather than a string compare.
    const MAX_CELLS: usize = 20_000;
    let (n, m) = (a.len(), b.len());
    if n == 0 || m == 0 || n.saturating_mul(m) > MAX_CELLS {
        return Vec::new();
    }
    let score = |i: usize, j: usize| -> Option<i64> {
        let s = similarity(&a[i], &b[j]);
        if s >= EDIT_SIMILARITY {
            Some((s * 1_000_000.0) as i64)
        } else {
            None
        }
    };
    let mut dp = vec![0i64; (n + 1) * (m + 1)];
    let at = |i: usize, j: usize| i * (m + 1) + j;
    for i in (0..n).rev() {
        for j in (0..m).rev() {
            let skip = dp[at(i + 1, j)].max(dp[at(i, j + 1)]);
            let take = score(i, j).map(|s| s + dp[at(i + 1, j + 1)]).unwrap_or(0);
            dp[at(i, j)] = skip.max(take);
        }
    }
    let mut out = Vec::new();
    let (mut i, mut j) = (0usize, 0usize);
    while i < n && j < m {
        if let Some(s) = score(i, j) {
            if s + dp[at(i + 1, j + 1)] >= dp[at(i + 1, j)].max(dp[at(i, j + 1)]) {
                out.push((i, j));
                i += 1;
                j += 1;
                continue;
            }
        }
        if dp[at(i + 1, j)] >= dp[at(i, j + 1)] {
            i += 1;
        } else {
            j += 1;
        }
    }
    out
}

fn align(base: &Partition, side: &Partition) -> Option<Alignment> {
    let bk: Vec<String> = base.parts.iter().map(|p| p.key.clone()).collect();
    let sk: Vec<String> = side.parts.iter().map(|p| p.key.clone()).collect();
    let pairs = lcs_pairs(&bk, &sk)?;

    let mut per_base = vec![Action::Deleted; base.parts.len()];
    let mut additions: Vec<(usize, usize)> = Vec::new();

    // Walk the gaps between consecutive anchors, plus the head and tail gaps.
    let mut bi = 0usize;
    let mut si = 0usize;
    let mut anchors = pairs.to_vec();
    anchors.push((base.parts.len(), side.parts.len())); // sentinel tail gap
    for (ab, as_) in anchors {
        // Inside a gap nothing matched exactly, so the question is which of the
        // side's statements is the EDITED form of which of base's. Pairing them
        // by position is what a line differ does and it is wrong here for the
        // same reason it is wrong there: a statement inserted at the top of the
        // gap shunts every later pairing by one, and each shunted pair then
        // looks like a delete beside an add. The order-preserving matching that
        // maximises similarity is the reading that does not depend on where the
        // insertion happened to land.
        let matched = best_matching(&bk[bi..ab], &sk[si..as_]);
        let mut taken: Vec<bool> = vec![false; as_ - si];
        for &(bo, so) in &matched {
            per_base[bi + bo] = Action::Edited(si + so);
            taken[so] = true;
        }
        for (so, t) in taken.iter().enumerate() {
            if !t {
                additions.push((bi, si + so));
            }
        }
        // Surplus base statements in this gap stay `Deleted`.
        if ab < base.parts.len() {
            // The keys agree; the BYTES may not, because a key drops leading
            // indentation so that a statement which only moved still matches
            // itself. A re-indentation is an edit — emitting base's columns for
            // it would re-indent text nobody asked to re-indent, which is a
            // loss and not a formatting nicety.
            per_base[ab] = if base.parts[ab].text == side.parts[as_].text {
                Action::Unchanged
            } else {
                Action::Edited(as_)
            };
        }
        bi = ab + 1;
        si = as_ + 1;
    }
    Some(Alignment {
        per_base,
        additions,
    })
}

// ---------------------------------------------------------------------------
// The fold
// ---------------------------------------------------------------------------

/// Three-way merge of a piece of text that is not a statement — the header, the
/// prelude, the tail, the footer.
fn merge_trivia(
    name: &str,
    b: &str,
    o: &str,
    t: &str,
    fmt: &ScopeMarkers<'_>,
    has_conflict: &mut bool,
) -> String {
    if o == t {
        return o.to_string();
    }
    if b == o {
        return t.to_string();
    }
    if b == t {
        return o.to_string();
    }
    if let Some(merged) = diffy_merge(b, o, t) {
        return merged;
    }
    *has_conflict = true;
    scoped_conflict_marker(name, Some(b), Some(o), Some(t), false, false, fmt)
}

// ---------------------------------------------------------------------------
// The one shape of same-gap insertion that is not a choice
// ---------------------------------------------------------------------------

/// May two blocks of statements inserted into the same gap both land, and if
/// so, what did each of them bind?
///
/// The default answer is no. Two independent insertions into one gap have no
/// separator between them, so every order is a program and none of them is one
/// a side wrote. Two shapes escape that, and they are
/// different arguments:
///
/// **Independent declarations**, always available. Every statement in both
/// blocks binds exactly one name and does nothing else observable; the blocks
/// bind disjoint names; and neither mentions a name the other binds. For
/// example: two sides each appending their own feature flags to a class
/// attribute block.
///
/// **Disjoint-write composition**, only under [`License::Footprint`]. The declaration gate
/// is a *sufficient* condition stated as a syntactic shape, and it refuses
/// several things it has no reason to: a helper `def` each side added, a
/// declaration whose body spans lines, a block mixing the two. What actually
/// makes an order unobservable is that neither block writes what the other
/// writes and neither writes what the other reads.
/// [`crate::binding::footprint`] answers `None` for anything whose effect it
/// cannot see, so a bare call, a `return`, an `if`, a `+=` or a decorated
/// definition still refuses the gap.
///
/// Two sides appending *calls* to a function body is refused under both, and
/// that is not an oversight: `flush()` and `retry()` read and write
/// whatever they touch, and this reader has no name for those effects.
fn same_gap_composition_licensed(
    mine: &[Part],
    yours: &[Part],
    license: License,
) -> Option<LicensedGap> {
    if mine.is_empty() || yours.is_empty() {
        return None;
    }
    if let Some(g) = independent_declarations(mine, yours) {
        return Some(g);
    }
    if license != License::Footprint {
        return None;
    }
    let cat = |ps: &[Part]| -> String {
        let mut s = String::new();
        for p in ps {
            s.push_str(&p.text);
            if !s.ends_with('\n') {
                s.push('\n');
            }
        }
        s
    };
    let (fm, fy) = (footprint(&cat(mine))?, footprint(&cat(yours))?);
    if !footprints_disjoint(&fm, &fy) {
        return None;
    }
    Some(LicensedGap {
        ours_binds: fm.defines.into_iter().collect(),
        theirs_binds: fy.defines.into_iter().collect(),
    })
}

/// The declaration gate, unchanged in meaning: every statement in both blocks
/// binds exactly one name and nothing else, the two blocks bind disjoint names,
/// and neither block mentions a name the other binds.
fn independent_declarations(mine: &[Part], yours: &[Part]) -> Option<LicensedGap> {
    use std::collections::HashSet;
    let names = |ps: &[Part]| -> Option<Vec<String>> {
        ps.iter().map(|p| declared_name(&p.text)).collect()
    };
    let (mn, yn) = (names(mine)?, names(yours)?);
    let mset: HashSet<&String> = mn.iter().collect();
    let yset: HashSet<&String> = yn.iter().collect();
    if mset.intersection(&yset).next().is_some() {
        return None;
    }
    let mentions = |ps: &[Part], who: &HashSet<&String>| -> bool {
        ps.iter().any(|p| {
            word_tokens(&p.text)
                .iter()
                .any(|w| who.contains(&w.to_string()))
        })
    };
    if mentions(mine, &yset) || mentions(yours, &mset) {
        return None;
    }
    Some(LicensedGap {
        ours_binds: mn,
        theirs_binds: yn,
    })
}

/// Two renderings of the same statement that differ only in the spaces BETWEEN
/// their tokens — same line count, same indentation on every line, same tokens
/// in the same order. Returns the winner, chosen by the bytes so that the
/// answer does not depend on which side is ours.
///
/// Leading whitespace is excluded from "formatting" on purpose: in an
/// indentation-scoped language a dedent can move a statement between blocks,
/// so calling that formatting would silently discard a structural edit.
fn formatting_tie(a: &str, b: &str) -> Option<String> {
    let (la, lb): (Vec<&str>, Vec<&str>) = (a.lines().collect(), b.lines().collect());
    if la.len() != lb.len() {
        return None;
    }
    for (x, y) in la.iter().zip(lb.iter()) {
        let indent = |s: &str| s.len() - s.trim_start().len();
        if indent(x) != indent(y) {
            return None;
        }
        if x.split_whitespace().ne(y.split_whitespace()) {
            return None;
        }
    }
    Some(if a <= b { a.to_string() } else { b.to_string() })
}

/// A side-independent sort key for a block of inserted statements.
fn key_of(parts: &[Part]) -> String {
    let mut out = String::new();
    for p in parts {
        out.push_str(&p.key);
    }
    out
}

/// A short human label for a statement, for conflict markers: the first line,
/// trimmed and clipped. A marker that names nothing sends the reader to the
/// whole file.
fn label(text: &str) -> String {
    let first = text.lines().find(|l| !l.trim().is_empty()).unwrap_or("");
    let t = first.trim();
    if t.chars().count() > 48 {
        let clipped: String = t.chars().take(45).collect();
        format!("{clipped}...")
    } else {
        t.to_string()
    }
}

/// Merge an entity body statement-wise, or `None` if this reader does not
/// understand the body well enough to be trusted with it.
///
/// `None` costs the caller the whole-entity conflict it would have raised
/// anyway, which is why every uncertainty in here answers `None` rather than
/// guessing.
pub(crate) fn statement_merge(
    base: &str,
    ours: &str,
    theirs: &str,
    fmt: &ScopeMarkers<'_>,
) -> Option<InnerMergeResult> {
    statement_merge_inner(
        base,
        ours,
        theirs,
        fmt,
        0,
        License::Refused,
        &mut Vec::new(),
        &mut Vec::new(),
    )
}

/// How much authority the fold has over two blocks inserted into the same gap.
///
/// The default is [`License::Refused`]: two independent insertions into one gap
/// have no separator between them, so every order is a program and none of them
/// is one a side wrote. The one exception the fold has
/// always made is `independent_declarations` — a shape where the two orders are
/// the same program.
///
/// [`License::Footprint`] widens that exception to any two blocks with disjoint
/// read/write sets, and it is granted by `v2::bind` and by nobody else, only on
/// a triple that is **already a conflict**. That is what keeps the pass one-way: a mode
/// that can only be entered from a conflict can only leave one.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum License {
    Refused,
    Footprint,
}

/// Evidence for one licensed composition: what each side's block binds.
#[derive(Debug, Clone)]
pub(crate) struct LicensedGap {
    pub ours_binds: Vec<String>,
    pub theirs_binds: Vec<String>,
}

/// The fold at an explicit license. `container.rs` needs this because a member
/// body is reached through the container merge rather than directly, so the
/// license has to travel with the call rather than with the entry point.
pub(crate) fn statement_merge_with(
    base: &str,
    ours: &str,
    theirs: &str,
    fmt: &ScopeMarkers<'_>,
    license: License,
    evidence: &mut Vec<LicensedGap>,
) -> Option<InnerMergeResult> {
    statement_merge_inner(
        base,
        ours,
        theirs,
        fmt,
        0,
        license,
        evidence,
        &mut Vec::new(),
    )
}

/// The fold, with disjoint-write composition available to the same-gap arm. Returns the
/// evidence for every composition the license paid for, so the caller can put
/// it on the findings channel — a resolution nobody can see the reason for is
/// not a resolution, it is a guess with better manners.
pub(crate) fn statement_merge_licensed(
    base: &str,
    ours: &str,
    theirs: &str,
    fmt: &ScopeMarkers<'_>,
) -> Option<(InnerMergeResult, Vec<LicensedGap>)> {
    let mut evidence = Vec::new();
    let r = statement_merge_inner(
        base,
        ours,
        theirs,
        fmt,
        0,
        License::Footprint,
        &mut evidence,
        &mut Vec::new(),
    )?;
    Some((r, evidence))
}

/// How far the fold may recurse. Depth 0 is the entity body, depth 1 the block
/// inside one of its statements, and so on down.
///
/// The bound is what makes termination a fact rather than an argument. The
/// recursion is NOT justified by "the input shrinks" — a body whose partition is
/// a single block statement recurses on text that may be very nearly itself —
/// so the depth counter is the well-founded measure, and it is the only one.
/// Three levels is where the evidence runs out in practice: past a nested `for`
/// inside an `if` inside a method, the partition is guessing about a grammar
/// nobody parsed.
const MAX_DEPTH: u8 = 3;

fn statement_merge_inner(
    base: &str,
    ours: &str,
    theirs: &str,
    fmt: &ScopeMarkers<'_>,
    depth: u8,
    license: License,
    evidence: &mut Vec<LicensedGap>,
    // Lines the expression fold composed, at this level and below. The
    // no-fabrication backstop licenses exactly these — see `fabricates_lines`.
    composed: &mut Vec<String>,
) -> Option<InnerMergeResult> {
    let b = partition(base)?;
    let o = partition(ours)?;
    let t = partition(theirs)?;

    // One statement per side is not a partition worth having AT THE BOTTOM: the
    // fold degenerates to the diff3 that already refused this body. It is worth
    // having above the bottom, because that one statement is a block, and the
    // level below it is where the two sides' edits become separable — a method
    // whose whole body is a single `if` is otherwise never looked inside.
    if b.parts.len() < 2 && o.parts.len() < 2 && t.parts.len() < 2 && depth >= MAX_DEPTH {
        return None;
    }

    let ours_align = align(&b, &o)?;
    let theirs_align = align(&b, &t)?;

    // Mint the claims. From here on a statement is reached only through the
    // claim that names it, and a claim is spent once.
    let base_claims: Vec<BasePart> = b.claims(BasePart::new);
    let ours_claims: Vec<OursPart> = o.claims(OursPart::new);
    let theirs_claims: Vec<TheirsPart> = t.claims(TheirsPart::new);

    let mut has_conflict = false;
    let mut out = String::new();
    out.push_str(&merge_trivia(
        "declaration",
        &b.header,
        &o.header,
        &t.header,
        fmt,
        &mut has_conflict,
    ));
    out.push_str(&merge_trivia(
        "body prelude",
        &b.prelude,
        &o.prelude,
        &t.prelude,
        fmt,
        &mut has_conflict,
    ));

    // Additions grouped by the gap they sit in.
    let mut ours_adds: HashMap<usize, Vec<usize>> = HashMap::new();
    for (gap, s) in &ours_align.additions {
        ours_adds.entry(*gap).or_default().push(*s);
    }
    let mut theirs_adds: HashMap<usize, Vec<usize>> = HashMap::new();
    for (gap, s) in &theirs_align.additions {
        theirs_adds.entry(*gap).or_default().push(*s);
    }

    let render = |part: &Part| -> String {
        let mut s = part.lead.clone();
        s.push_str(&part.text);
        s
    };

    // Two independent insertions into the same gap have no separator between
    // them: every order is a program, and none of them is
    // one a side wrote. Identical insertions are not two insertions — and
    // neither are two blocks of DECLARATIONS that cannot see each other, which
    // is the one shape where "what order" is a question with no answer to get
    // wrong (see `independent_declarations`).
    let emit_gap =
        |gap: usize, out: &mut String, has_conflict: &mut bool, licensed: &mut Vec<LicensedGap>| {
            let pick = |adds: &HashMap<usize, Vec<usize>>,
                        parts: &[Part],
                        idx: &dyn Fn(usize) -> usize|
             -> Vec<Part> {
                adds.get(&gap)
                    .map(|v| v.iter().map(|&s| parts[idx(s)].clone()).collect())
                    .unwrap_or_default()
            };
            let mine_parts = pick(&ours_adds, &o.parts, &|s| ours_claims[s].index());
            let yours_parts = pick(&theirs_adds, &t.parts, &|s| theirs_claims[s].index());
            let cat = |ps: &[Part]| -> String { ps.iter().map(render).collect() };
            let (mine, yours) = (cat(&mine_parts), cat(&yours_parts));
            match (mine.is_empty(), yours.is_empty()) {
                (true, true) => {}
                (false, true) => out.push_str(&mine),
                (true, false) => out.push_str(&yours),
                (false, false) => {
                    if mine == yours {
                        out.push_str(&mine);
                    } else if let Some(binds) =
                        same_gap_composition_licensed(&mine_parts, &yours_parts, license)
                    {
                        licensed.push(binds);
                        // Both blocks land, in the order their own bytes decide —
                        // never in the order the caller happened to name the sides,
                        // so the merge is the same from either direction.
                        let (first, second) = if key_of(&mine_parts) <= key_of(&yours_parts) {
                            (&mine, &yours)
                        } else {
                            (&yours, &mine)
                        };
                        out.push_str(first);
                        out.push_str(second);
                    } else {
                        *has_conflict = true;
                        out.push_str(&scoped_conflict_marker(
                            "inserted statements",
                            None,
                            Some(&mine),
                            Some(&yours),
                            false,
                            false,
                            fmt,
                        ));
                    }
                }
            }
        };

    for (i, claim) in base_claims.iter().enumerate() {
        emit_gap(i, &mut out, &mut has_conflict, evidence);
        let bp = &b.parts[claim.index()];
        // Action and statement resolved together, once: from here on "this side
        // edited" and "here is what it edited it to" are the same fact.
        // `align(&b, ..)` returns one action per base statement, and `i` walks
        // `base_claims`, which is one claim per base statement — so `per_base[i]`
        // is in range. The claim indices are this side's own, see `resolve`.
        let ao = SideEdit::resolve(&ours_align.per_base[i], &o.parts, |s| {
            // This side's own claim vector, indexed by this side's own action.
            ours_claims[s].index()
        });
        let at = SideEdit::resolve(&theirs_align.per_base[i], &t.parts, |s| {
            // Same argument, theirs' side of it.
            theirs_claims[s].index()
        });
        let (op, tp) = (ao.part(), at.part());
        let name = label(&bp.text);

        // The lead is decided by the versions that still HAVE the statement. A
        // version that deleted it did not empty the gap in front of it.
        let lead = match (&ao, &at) {
            (SideEdit::Deleted, SideEdit::Deleted) => None,
            (SideEdit::Deleted, _) => Some(tp.map(|p| p.lead.clone()).unwrap_or(bp.lead.clone())),
            (_, SideEdit::Deleted) => Some(op.map(|p| p.lead.clone()).unwrap_or(bp.lead.clone())),
            _ => {
                let lo = op.map(|p| p.lead.as_str()).unwrap_or(&bp.lead);
                let lt = tp.map(|p| p.lead.as_str()).unwrap_or(&bp.lead);
                Some(merge_trivia(
                    &format!("before {name}"),
                    &bp.lead,
                    lo,
                    lt,
                    fmt,
                    &mut has_conflict,
                ))
            }
        };

        // One arm per (ours, theirs) action pair over
        // {UNCHANGED, EDITED, DELETED}.
        let body: Option<String> = match (&ao, &at) {
            (SideEdit::Unchanged, SideEdit::Unchanged) => Some(bp.text.clone()),
            (SideEdit::Unchanged, SideEdit::Edited(pt)) => Some(pt.text.clone()),
            (SideEdit::Edited(po), SideEdit::Unchanged) => Some(po.text.clone()),
            (SideEdit::Edited(eo), SideEdit::Edited(et)) => {
                let (po, pt) = (&eo.text, &et.text);
                if po == pt {
                    Some(po.clone())
                } else if let Some(text) = formatting_tie(po, pt) {
                    // Same statement, same columns, same tokens, different
                    // spaces between them. There is no program here to get
                    // wrong, so there is nothing for a human to decide — and the
                    // winner is chosen by the bytes rather than by which side
                    // the caller happened to name first.
                    Some(text)
                } else {
                    // Depth 1 is enough: what is inside one statement is text,
                    // and text is diff3's leaf.
                    // `git merge-file` is deliberately NOT the second opinion
                    // here, though it is one level up. Spawning it costs a
                    // subprocess per call, and a body has tens of statements
                    // with this fold recursing into each one, so the same
                    // tail-case tiebreaker turns into a per-statement
                    // subprocess. Measurement showed that cost without a
                    // matching gain in resolutions, since diff3 is already
                    // inside the process at this point.
                    diffy_merge(&bp.text, po, pt)
                        // The statement is itself a block — an `if`, a `for`, a
                        // `try` — and the same fold reads it. Bounded, and only
                        // when it comes back CLEAN: a nested conflict is the
                        // conflict this arm was already going to raise.
                        .or_else(|| {
                            if depth >= MAX_DEPTH {
                                return None;
                            }
                            statement_merge_inner(
                                &bp.text,
                                po,
                                pt,
                                fmt,
                                depth + 1,
                                license,
                                evidence,
                                composed,
                            )
                            .filter(|r| !r.has_conflicts)
                            .map(|r| r.content)
                        })
                        // The last zoom. Both sides edited this one statement,
                        // diff3 refused it, and it is not a block the fold can
                        // separate — so the statement is tiled into TOKENS and
                        // the two token edits are composed if, and only if, a
                        // base token neither side touched separates them.
                        // Reached from here and nowhere else, so the verdict
                        // it can change is CONFLICT → clean and nothing else.
                        .or_else(|| {
                            let c = crate::expression::expression_merge(&bp.text, po, pt)?;
                            composed.extend(c.composed_lines);
                            Some(c.text)
                        })
                        .or_else(|| {
                            has_conflict = true;
                            Some(scoped_conflict_marker(
                                &name,
                                Some(&bp.text),
                                Some(po),
                                Some(pt),
                                false,
                                false,
                                fmt,
                            ))
                        })
                }
            }
            (SideEdit::Unchanged, SideEdit::Deleted) | (SideEdit::Deleted, SideEdit::Unchanged) => {
                None
            }
            (SideEdit::Deleted, SideEdit::Deleted) => None,
            (SideEdit::Edited(po), SideEdit::Deleted) => {
                has_conflict = true;
                Some(scoped_conflict_marker(
                    &name,
                    Some(&bp.text),
                    Some(&po.text),
                    None,
                    false,
                    true,
                    fmt,
                ))
            }
            (SideEdit::Deleted, SideEdit::Edited(pt)) => {
                has_conflict = true;
                Some(scoped_conflict_marker(
                    &name,
                    Some(&bp.text),
                    None,
                    Some(&pt.text),
                    true,
                    false,
                    fmt,
                ))
            }
        };

        if let Some(text) = body {
            if let Some(lead) = lead {
                out.push_str(&lead);
            }
            out.push_str(&text);
            if !text.ends_with('\n') {
                out.push('\n');
            }
        }
    }
    emit_gap(base_claims.len(), &mut out, &mut has_conflict, evidence);

    out.push_str(&merge_trivia(
        "trailing statements",
        &b.tail,
        &o.tail,
        &t.tail,
        fmt,
        &mut has_conflict,
    ));
    out.push_str(&merge_trivia(
        "closing",
        &b.footer,
        &o.footer,
        &t.footer,
        fmt,
        &mut has_conflict,
    ));
    if !ours.ends_with('\n') {
        while out.ends_with('\n') {
            out.pop();
        }
    }

    // Two backstops on the finished bytes, because a partition is only as
    // honest as the reader that produced it.
    //
    // (1) Nothing all three versions agreed on may be missing — `container.rs`'s
    //     predicate, unchanged, and the one weave is measured on.
    // (2) Nothing may be present that no version wrote. A fold cannot fabricate
    //     a line, so a fabricated line means the fold is not what ran.
    if drops_unanimous_lines(base, ours, theirs, &out)
        || fabricates_lines(base, ours, theirs, &out, composed)
    {
        return None;
    }

    Some(InnerMergeResult {
        content: out,
        has_conflicts: has_conflict,
    })
}

/// Does `out` contain a non-blank line no version wrote and nothing licensed?
///
/// Conflict markers are the one thing this merge is allowed to invent, so they
/// and their contents are exempt — everything outside them must be somebody's
/// own bytes.
///
/// `licensed` is the exception the expression fold pays for. A token
/// composition is, by definition, a line that no version wrote — that is what
/// composing means — so a backstop that only knows the three inputs would veto
/// every one of them, and a backstop widened to "anything the fold felt like"
/// would stop being a backstop. The middle is this: `expression::expression_merge`
/// reports the exact lines it created, they are the only new lines admitted,
/// and every other new line still fails. A line that appears in the output
/// which the fold cannot account for is still evidence that the fold is not
/// what ran.
fn fabricates_lines(base: &str, ours: &str, theirs: &str, out: &str, licensed: &[String]) -> bool {
    use std::collections::HashSet;
    let mut known: HashSet<&str> = HashSet::new();
    for src in [base, ours, theirs] {
        for l in src.lines() {
            known.insert(l.trim_end());
        }
    }
    for l in licensed {
        known.insert(l.as_str());
    }
    out.lines().any(|l| {
        let t = l.trim_end();
        if t.trim().is_empty() {
            return false;
        }
        let s = t.trim_start();
        if s.starts_with('<') || s.starts_with('=') || s.starts_with('>') || s.starts_with('|') {
            // A marker line, or a line that begins with one of the characters a
            // marker begins with — either way not evidence of fabrication.
            return false;
        }
        if crate::conflict::refusal_body(s).is_some() {
            // The marker's own refusal line. It is part of the conflict's
            // rendering, not of the program.
            return false;
        }
        !known.contains(t)
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::conflict::MarkerFormat;

    const SAMPLES: &[&str] = &[
        // python
        "def f(x):\n    total = 0\n    for i in x:\n        total += i\n\n    # done\n    return total\n",
        // typescript
        "function f(x: number[]): number {\n  let total = 0;\n  for (const i of x) {\n    total += i;\n  }\n\n  // done\n  return total;\n}\n",
        // rust
        "fn f(x: &[i32]) -> i32 {\n    let mut total = 0;\n    for i in x {\n        total += i;\n    }\n\n    total\n}\n",
        // java
        "public int f(int[] x) {\n    int total = 0;\n    for (int i : x) {\n        total += i;\n    }\n    if (total > 0) {\n        total--;\n    } else {\n        total++;\n    }\n    return total;\n}\n",
        // go
        "func f(x []int) int {\n\ttotal := 0\n\tfor _, i := range x {\n\t\ttotal += i\n\t}\n\treturn total\n}\n",
        // continuation lines that indentation alone would split
        "fn g() {\n    foo(a,\nb);\n    bar();\n}\n",
        // rust lifetimes: an apostrophe that opens no string
        "fn h<'a>(s: &'a str) -> &'a str {\n    let t = s.trim();\n    t\n}\n",
    ];

    /// The property everything else rests on.
    #[test]
    fn a_partition_tiles_the_body_it_came_from() {
        for content in SAMPLES {
            let p = partition(content).unwrap_or_else(|| panic!("partitions: {content:?}"));
            let mut rebuilt = p.header.clone();
            rebuilt.push_str(&p.prelude);
            for part in &p.parts {
                rebuilt.push_str(&part.lead);
                rebuilt.push_str(&part.text);
            }
            rebuilt.push_str(&p.tail);
            rebuilt.push_str(&p.footer);
            assert_eq!(rebuilt, *content, "partition lost or duplicated text");
        }
    }

    #[test]
    fn a_continuation_line_does_not_start_a_statement() {
        let p = partition("fn g() {\n    foo(a,\nb);\n    bar();\n}\n").unwrap();
        assert_eq!(p.parts.len(), 2, "{:?}", p.parts);
        assert_eq!(p.parts[0].text, "    foo(a,\nb);\n");
    }

    #[test]
    fn an_else_arm_stays_with_its_if() {
        let p = partition(SAMPLES[3]).unwrap();
        let keys: Vec<&str> = p.parts.iter().map(|x| x.key.as_str()).collect();
        assert_eq!(keys.len(), 4, "{keys:?}");
        assert!(keys[2].starts_with("if (total > 0) {"), "{keys:?}");
        assert!(keys[2].contains("} else {"), "{keys:?}");
    }

    #[test]
    fn disjoint_statement_edits_merge() {
        let base = "fn f() {\n    let a = 1;\n    let b = 2;\n    let c = 3;\n}\n";
        let ours = "fn f() {\n    let a = 11;\n    let b = 2;\n    let c = 3;\n}\n";
        let theirs = "fn f() {\n    let a = 1;\n    let b = 2;\n    let c = 33;\n}\n";
        let r = statement_merge(
            base,
            ours,
            theirs,
            &ScopeMarkers::bare(&MarkerFormat::default()),
        )
        .expect("merges");
        assert!(!r.has_conflicts);
        assert_eq!(
            r.content,
            "fn f() {\n    let a = 11;\n    let b = 2;\n    let c = 33;\n}\n"
        );
    }

    #[test]
    fn a_move_is_not_a_conflict_with_an_edit_elsewhere() {
        let base = "fn f() {\n    a();\n    b();\n    c();\n}\n";
        // ours moves a() to the end; theirs edits b()
        let ours = "fn f() {\n    b();\n    c();\n    a();\n}\n";
        let theirs = "fn f() {\n    a();\n    b(1);\n    c();\n}\n";
        let r = statement_merge(
            base,
            ours,
            theirs,
            &ScopeMarkers::bare(&MarkerFormat::default()),
        )
        .expect("merges");
        assert!(!r.has_conflicts, "{}", r.content);
        assert_eq!(r.content, "fn f() {\n    b(1);\n    c();\n    a();\n}\n");
    }

    #[test]
    fn two_insertions_into_one_gap_are_a_conflict() {
        let base = "fn f() {\n    a();\n    z();\n}\n";
        let ours = "fn f() {\n    a();\n    m();\n    z();\n}\n";
        let theirs = "fn f() {\n    a();\n    n();\n    z();\n}\n";
        let r = statement_merge(
            base,
            ours,
            theirs,
            &ScopeMarkers::bare(&MarkerFormat::default()),
        )
        .expect("merges");
        assert!(r.has_conflicts, "{}", r.content);
    }

    #[test]
    fn insertions_into_different_gaps_both_land() {
        let base = "fn f() {\n    a();\n    z();\n    q();\n}\n";
        let ours = "fn f() {\n    a();\n    m();\n    z();\n    q();\n}\n";
        let theirs = "fn f() {\n    a();\n    z();\n    n();\n    q();\n}\n";
        let r = statement_merge(
            base,
            ours,
            theirs,
            &ScopeMarkers::bare(&MarkerFormat::default()),
        )
        .expect("merges");
        assert!(!r.has_conflicts, "{}", r.content);
        assert_eq!(
            r.content,
            "fn f() {\n    a();\n    m();\n    z();\n    n();\n    q();\n}\n"
        );
    }

    #[test]
    fn delete_versus_edit_of_one_statement_conflicts_on_that_statement() {
        let base = "fn f() {\n    a();\n    b();\n    c();\n}\n";
        let ours = "fn f() {\n    a();\n    c();\n}\n";
        let theirs = "fn f() {\n    a();\n    b(2);\n    c();\n}\n";
        let r = statement_merge(
            base,
            ours,
            theirs,
            &ScopeMarkers::bare(&MarkerFormat::default()),
        )
        .expect("merges");
        assert!(r.has_conflicts);
        assert!(r.content.contains("a();"), "{}", r.content);
        assert!(r.content.contains("c();"), "{}", r.content);
    }

    /// An unterminated literal is unrecoverable; an unbalanced bracket count is
    /// not. The first means everything after it was read as code that is not
    /// code; the second means the text is a fragment of something larger, which
    /// is what the recursive arm hands itself on every call.
    #[test]
    fn an_unterminated_literal_is_refused_but_a_fragment_is_not() {
        assert!(depths(&["fn f() {", "    /* open"]).is_none());
        assert!(
            depths(&["    a();", "}"]).is_some(),
            "a fragment still scans"
        );
        let d = depths(&["fn f() {", "    a();"]).expect("a fragment still scans");
        assert_eq!(d, vec![0, 1], "depth is reported, not judged");
    }

    /// The nesting level a fragment's statements sit at is the fragment's own,
    /// not zero — otherwise a block sliced out of a method has no statements at
    /// all and the fold never looks inside it.
    #[test]
    fn statements_are_found_at_the_fragments_own_level() {
        let p = partition("    if x:\n        a()\n        b()\n").expect("partitions");
        let keys: Vec<&str> = p.parts.iter().map(|x| x.key.as_str()).collect();
        assert_eq!(keys, vec!["a()\n", "b()\n"], "{keys:?}");
    }

    /// The same triple gives the same bytes, every time.
    #[test]
    fn the_statement_merge_is_a_function_of_its_inputs() {
        let base = "fn f() {\n    a();\n    b();\n    c();\n    d();\n}\n";
        let ours = "fn f() {\n    a2();\n    b();\n    c();\n    x();\n    d();\n}\n";
        let theirs = "fn f() {\n    a();\n    b();\n    c2();\n    d();\n}\n";
        let first = statement_merge(
            base,
            ours,
            theirs,
            &ScopeMarkers::bare(&MarkerFormat::default()),
        )
        .map(|r| (r.content, r.has_conflicts));
        for _ in 0..24 {
            let again = statement_merge(
                base,
                ours,
                theirs,
                &ScopeMarkers::bare(&MarkerFormat::default()),
            )
            .map(|r| (r.content, r.has_conflicts));
            assert_eq!(first, again, "statement merge is not a function");
        }
    }
}
